repos:
  # 0. Pre-commit official hooks (cleanup, merge conflicts, etc.)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-docstring-first
        files: \.py$
      - id: check-added-large-files
        files: \.py$
      - id: check-case-conflict
        files: \.py$
      - id: check-merge-conflict
        files: \.py$
      - id: debug-statements
        files: \.py$
      - id: end-of-file-fixer
        files: \.py$
      - id: mixed-line-ending
        files: \.py$
      - id: trailing-whitespace
        files: \.py$
        args: ["--markdown-linebreak-ext=md"]

        
  # ----------------------------
  # Ruff (lint + fix)
  # ----------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      # Lint first (with autofix)
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]

      # Then format
      - id: ruff-format

  # ----------------------------
  # Type checking (ty)
  # ----------------------------
  - repo: local
    hooks:
      - id: ty-warning
        name: ty (warning only)
        entry: bash -c 'ty check || true'
        language: system
        pass_filenames: false


  # ----------------------------
  # Tyest coverage (manual only)
  # ----------------------------
  - repo: local
    hooks:
      - id: pytest
        name: pytest with coverage
        entry: pytest --cov=pyPLUTO --cov-fail-under=45
        language: system
        types: [python]
        stages: [manual]
        pass_filenames: false