repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    files: \.py$
  - id: check-case-conflict
    files: \.py$
  - id: check-merge-conflict
    files: \.py$
  - id: debug-statements
    files: \.py$
  - id: end-of-file-fixer
    files: \.py$
  - id: mixed-line-ending
    files: \.py$
  - id: trailing-whitespace
    files: \.py$

    args: ["--markdown-linebreak-ext=md"]
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    files: \.py$