[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyPLUTO"
version = "1.0.0"
description = "PyPLUTO: Plotting routines for PLUTO"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
    { name = "G. Mattia", email = "mattia@mpia.de" },
    { name = "D. Crocco" },
    { name = "D. Melon Fuksman" },
    { name = "M. Bugli" },
    { name = "V. Berta" },
    { name = "E. Puzzoni" },
    { name = "A. Mignone" },
    { name = "B. Vaidya" }
]
dependencies = [
    "numpy",
    "matplotlib>=3.5",
    "scipy",
    "pandas",
    "h5py",
    "PyQt6"
]
[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-automodapi",
    "numpydoc"
]
test = [
    "pytest",
    "pytest-doctestplus",
    "flake8",
    "codecov",
    "pytest-cov"
]
dev = [
    "black",
    "isort",
    "pre-commit"
]

[tool.setuptools.packages.find]
where = ["Src"]
