import subprocess
from pathlib import Path

import pytest
from PIL import Image, ImageChops

EXAMPLES_DIR = (Path(__file__).parent / "../Examples").resolve()
REFERENCE_DIR = (Path(__file__).parent / "Ref_figs").resolve()


def list_example_scripts():
    """Return a list of Python scripts in ../Examples."""
    scripts = sorted(EXAMPLES_DIR.glob("*.py"))
    if not scripts:
        pytest.skip("No example scripts found in ../Examples")
    return scripts


def run_example(script: Path):
    """Run a single Python example script."""
    subprocess.run(["python", str(script)], check=True)


def images_identical(img1_path, img2_path) -> bool:
    """Return True if two images are pixel-identical."""
    with Image.open(img1_path) as img1, Image.open(img2_path) as img2:
        if img1.size != img2.size or img1.mode != img2.mode:
            return False
        diff = ImageChops.difference(img1, img2)
        return diff.getbbox() is None


@pytest.mark.parametrize("script", list_example_scripts())
def test_example(script):
    """
    Run one example script and compare its generated images
    with the reference ones in the current directory.
    Each example appears as a separate pytest test.
    """
    run_example(script)

    generated_images = sorted(EXAMPLES_DIR.glob("*.png"))
    reference_images = sorted(REFERENCE_DIR.glob("*.png"))

    assert generated_images, f"No images generated by {script.name}"
    assert reference_images, "No reference images found in current directory"
    assert len(generated_images) == len(reference_images), (
        f"{script.name}: different number of images "
        f"({len(generated_images)} generated vs {len(reference_images)} reference)"
    )

    mismatches = []
    for gen_img, ref_img in zip(
        generated_images, reference_images, strict=False
    ):
        if not images_identical(gen_img, ref_img):
            mismatches.append(gen_img.name)

    assert not mismatches, (
        f"{script.name}: mismatched images {', '.join(mismatches)}"
    )
