"""Run the examples and ensure that the images are the same pixel by pixel."""

import shutil
import subprocess
import sys
from pathlib import Path

import pytest
from PIL import Image, ImageChops, ImageSequence

ROOT_DIR = Path(__file__).parent.parent.resolve()
EXAMPLES_DIR = (ROOT_DIR / "Examples").resolve()
REFERENCE_DIR = (Path(__file__).parent / "Ref_figs").resolve()
OUTPUT_PATTERNS = ("*.png", "*.gif")


def list_example_scripts() -> list[Path]:
    """Return a list of Python scripts in ../Examples."""
    scripts = sorted(EXAMPLES_DIR.glob("*.py"))
    if not scripts:
        pytest.skip("No example scripts found in ../Examples")
    return scripts


def run_example_in_sandbox(script: Path, tmp_path: Path) -> Path:
    """Copy Examples directory into a private sandbox and run the script there.

    The script remains unmodified and still writes inside an Examples directory.
    Pre-existing output files (PNGs, GIFs) are removed after the copy so that
    only images produced by this script's run are left to compare.
    """
    sandbox_root = tmp_path / "project"
    sandbox_examples = sandbox_root / "Examples"

    shutil.copytree(EXAMPLES_DIR, sandbox_examples)
    for pattern in OUTPUT_PATTERNS:
        for stale_file in sandbox_examples.glob(pattern):
            stale_file.unlink()

    sandbox_script = sandbox_examples / script.name

    subprocess.run(
        [sys.executable, str(sandbox_script)],
        check=True,
        cwd=sandbox_examples,
    )

    return sandbox_examples


def compare_images(gen_path: Path, ref_path: Path) -> str | None:
    """Return None if two images are pixel-identical, else a diff description.

    Handles both static images and multi-frame ones (e.g. GIFs) by comparing
    frame by frame. Frames are compared as rendered RGBA pixels rather than
    raw encoding, since GIF palette layout can differ frame-to-frame despite
    the same visual content.
    """
    with Image.open(gen_path) as gen_img, Image.open(ref_path) as ref_img:
        gen_frames = list(ImageSequence.Iterator(gen_img))
        ref_frames = list(ImageSequence.Iterator(ref_img))

        if len(gen_frames) != len(ref_frames):
            return (
                f"frame count differs (generated {len(gen_frames)} "
                f"vs reference {len(ref_frames)})"
            )

        for i, (gen_frame, ref_frame) in enumerate(
            zip(gen_frames, ref_frames, strict=True)
        ):
            gen_frame = gen_frame.convert("RGBA")
            ref_frame = ref_frame.convert("RGBA")
            if gen_frame.size != ref_frame.size:
                return (
                    f"frame {i} size differs (generated {gen_frame.size} "
                    f"vs reference {ref_frame.size})"
                )
            diff = ImageChops.difference(gen_frame, ref_frame)
            bbox = diff.getbbox()
            if bbox is not None:
                return f"frame {i} pixels differ within region {bbox}"

    return None


@pytest.mark.parametrize("script", list_example_scripts())
def test_example(script: Path, tmp_path: Path) -> None:
    """Run and compare the script-generated images.

    Run one example script in an isolated copy of Examples/ and compare its
    generated images with the reference ones, matched by filename.
    """
    sandbox_examples = run_example_in_sandbox(script, tmp_path)

    gen_images = sorted(
        f for pattern in OUTPUT_PATTERNS for f in sandbox_examples.glob(pattern)
    )
    assert gen_images, f"No images generated by {script.name}"

    mismatches = []
    for gen_img in gen_images:
        ref_img = REFERENCE_DIR / gen_img.name
        if not ref_img.exists():
            mismatches.append(
                f"{gen_img.name}: no reference image in {REFERENCE_DIR}"
            )
            continue
        reason = compare_images(gen_img, ref_img)
        if reason is not None:
            mismatches.append(f"{gen_img.name}: {reason}")

    assert not mismatches, f"{script.name}: " + "; ".join(mismatches)
