"""Run the examples and ensure that the images are the same pixel by pixel."""

import shutil
import subprocess
import sys
from pathlib import Path

import os
import os

import pytest
from PIL import Image, ImageChops

ROOT_DIR = Path(__file__).parent.parent.resolve()
EXAMPLES_DIR = (ROOT_DIR / "Examples").resolve()
REFERENCE_DIR = (Path(__file__).parent / "Ref_figs").resolve()


def list_example_scripts() -> list[Path]:
    """Return a list of Python scripts in ../Examples."""
    scripts = sorted(EXAMPLES_DIR.glob("*.py"))
    if not scripts:
        pytest.skip("No example scripts found in ../Examples")
    return scripts


def run_example_in_sandbox(script: Path, tmp_path: Path) -> Path:
    """Copy Examples directory into a private sandbox and run the script there.

    The script remains unmodified and still writes inside an Examples directory.
    """
    sandbox_root = tmp_path / "project"
    sandbox_examples = sandbox_root / "Examples"

    shutil.copytree(EXAMPLES_DIR, sandbox_examples)

    sandbox_script = sandbox_examples / script.name

    subprocess.run(
        [sys.executable, str(sandbox_script)],
        check=True,
        cwd=sandbox_examples,
    )

    return sandbox_examples


def images_identical(img1_path: Path, img2_path: Path) -> bool:
    """Return True if two images are pixel-identical."""
    with Image.open(img1_path) as img1, Image.open(img2_path) as img2:
        if img1.size != img2.size or img1.mode != img2.mode:
            return False
        diff = ImageChops.difference(img1, img2)
        return diff.getbbox() is None


@pytest.mark.parametrize("script", list_example_scripts())
def test_example(script: Path, tmp_path: Path) -> None:
    """Run and compare the script-generated images.

    Run one example script in an isolated copy of Examples/ and compare its
    generated images with the reference ones.
    """
    sandbox_examples = run_example_in_sandbox(script, tmp_path)

    gen_images = sorted(sandbox_examples.glob("*.png"))
    ref_images = sorted(REFERENCE_DIR.glob("*.png"))

    assert gen_images, f"No images generated by {script.name}"
    assert ref_images, "No reference images found in current directory"
    assert len(gen_images) == len(ref_images), (
        f"{script.name}: different number of images "
        f"({len(gen_images)} generated vs {len(ref_images)} reference)"
    )

    mismatches = []
    for gen_img, ref_img in zip(gen_images, ref_images, strict=False):
        if not images_identical(gen_img, ref_img):
            mismatches.append(gen_img.name)

    assert not mismatches, (
        f"{script.name}: mismatched images {', '.join(mismatches)}"
    )
