name: Badge Generator

on:
  push:
  pull_request:

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_devs.txt

      - name: Install pyPLUTO
        run: |
          python -m pip install .

      - name: Run tests and generate coverage report
        run: |
          pytest --maxfail=5 --disable-warnings -q
          coverage xml -o coverage.xml
          pylint --output-format=text > pylint_output.txt
          interrogate . --output-format text > interrogate_output.txt

      - name: Generate badges
        run: |
          python Utils/generate_badges.py --coverage-xml coverage.xml --pylint-output pylint_output.txt --interrogate-output interrogate_output.txt --output-dir badges

      - name: Upload badges to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: badges
          path: badges/
