name: Badge Generator

on:
  push:
  pull_request:

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Install pyPLUTO
        run: |
          python -m pip install .

      - name: Run Tests with Coverage
        run: |
            coverage erase
            coverage run -m pytest
      - name: Report Coverage
        run: |
            coverage report --show-missing
            coverage xml -o Docs/Badges/coverage.xml

      - name: Run static checks (coverage, pylint, interrogate)
        run: python coverage_tests.py
