name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      # Install dependencies
      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black isort

      # Run pre-commit hooks
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

      # Debug file changes
      - name: Check for uncommitted changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Uncommitted changes detected after pre-commit hooks:"
            git diff
            exit 1
          else
            echo "No uncommitted changes detected."
          fi
