name: Check code style

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Set up Python and uv
      - name: Set up Python and uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: 3.12
          prune-cache: false

      - name: Sync environment
        run: uv sync --group dev

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.9.5

      # Run pre-commit hooks
      - name: Run pre-commit
        run: uv run --no-sync pre-commit run --all-files
