name: Build Documentation

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: [3.10, 3.11, 3.12]

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Docs/requirements.txt

      - name: Build documentation
        run: |
          sphinx-build -b html Docs/ Docs/_build/html

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html
          path: Docs/_build/html