name: Windows Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2022
          - windows-2025
        python-version: ["3.11","3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Clean untracked files & bytecode
        shell: pwsh
        run: |
          git clean -xfd
        #  Get-ChildItem -Path . -Include *.pyc -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue
        #  Get-ChildItem -Path . -Include __pycache__ -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: ${{ matrix.python-version }}
          prune-cache: false

      - name: Sync environment
        run: uv sync --all-extras --all-groups

      - name: Run Tests
        run: uv run --no-sync pytest -v ./Tests
