name: Tests on Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2022
          - windows-2025
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean untracked files & bytecode
        run: |
          # remove any stray compiled or cached files
          git clean -xfd
          # Purge any lingering pyc/__pycache__
          Get-ChildItem -Path . -Include *.pyc -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue
          Get-ChildItem -Path . -Include __pycache__ -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
        shell: pwsh

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Install pyPLUTO in editable mode
        run: |
          # ensure any old install is removed
          pip uninstall -y pyPLUTO || true
          pip install -e .

      - name: Show import path (debug)
        run: |
          python - <<'PYCODE'
          import pyPLUTO
          print("pyPLUTO loaded from:", pyPLUTO.__file__)
          PYCODE

      - name: Run Tests
        run: |
          # force pytest to load from workdir
          set PYTHONPATH=.
          pytest -v
        working-directory: ./Tests
