name: Run Tests on Multiple Python Versions and Platforms

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-20.04   # Ubuntu 20.04
          - ubuntu-22.04   # Ubuntu 22.04
          - macOS-13
          - macOS-14
          - macOS-15
          - windows-2019   # Windows Server 2019 (equivalent to Windows 10)
          - windows-2022   # Windows Server 2022 (latest)
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Docs/requirements.txt pytest

      - name: Install pyPLUTO
        run: |
          python -m pip install .

      - name: List files in Tests directory
        run: ls -R Tests/

      - name: Print working directory
        run: pwd

      - name: Run Tests
        run: pytest
        working-directory: ./Tests

      - name: Run Examples
        run: |
          echo "Running example scripts..."
          for example in Examples/*.py; do
            python "$example"
          done
