name: Tests on Windows

on:
  push:
    #branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2022
          - windows-2025
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean untracked files & bytecode
        shell: pwsh
        run: |
          git clean -xfd
        #  Get-ChildItem -Path . -Include *.pyc -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue
        #  Get-ChildItem -Path . -Include __pycache__ -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Install pyPLUTO in editable mode
        run: |
          pip uninstall -y pyPLUTO || true
          pip install -e .

      - name: Run Tests
        shell: pwsh
        env:
          PYTHONPATH: .
        run: |
          pytest -v
        working-directory: ./Tests

