name: Test on Cygwin or WSL

on:
  push:
    branches:
     - master
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Detect Cygwin or WSL
        id: env_check
        run: |
          if uname | grep -i "cygwin" > /dev/null 2>&1; then
            echo "env=cygwin" >> $GITHUB_ENV
            echo "Detected Cygwin on $(uname -a)"
          elif uname | grep -i "linux" > /dev/null 2>&1; then
            echo "env=wsl" >> $GITHUB_ENV
            echo "Detected WSL on $(uname -a)"
          else
            echo "env=none" >> $GITHUB_ENV
            echo "No Cygwin or WSL detected."
          fi
        shell: bash

      - name: Run Tests
        if: env.env != 'none'
        run: |
          echo "Running tests on environment: $env"
          pytest
